### PR TITLE
Ben's patch to use router for communicating with kafka-scheduler

### PR DESCRIPTION
**Pull request by dmitrypekar**
Hey, 

I've fixed a patch to be working.
I've tested against http://benw-13-elasticloa-1py8q8fyiw6li-1399817560.us-west-2.elb.amazonaws.com/
DCOS cluster using new CLI. 

dcos kafka status gots 500.
when going directly to http://benw-13-elasticloa-1py8q8fyiw6li-1399817560.us-west-2.elb.amazonaws.com/service/kafka/ I also got 500 for any suburl.

It reams that API Proxy has some problem.
Please __do not merge__ until retested.

### CODE REVIEW

**Comment by BenWhitehead** [comment]
This doesn't appear to work in python 3.

I cloned https://github.com/dmitrypekar/dcos-kafka master and followed the instructions in readme.rst and got the following traceback.
```
# dcos kafka help
Traceback (most recent call last):
  File "/tmp/dcos-kafka/env/bin/dcos-kafka", line 9, in <module>
    load_entry_point('dcos-kafka==0.1.0', 'console_scripts', 'dcos-kafka')()
  File "/tmp/dcos-kafka/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/dcos-kafka/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/tmp/dcos-kafka/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/tmp/dcos-kafka/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/dcos-kafka/dcos_kafka/cli.py", line 7, in <module>
    import urlparse
ImportError: No module named 'urlparse'
```
The patch I provided is just a small recommendation from a colleague here that knows some python (I don't know python at all) so it may not be comprehensive.

Also, running `tox` from the project checkout directory fails.

**Comment by dmitrypekar** [comment]
Hi Ben. I've fixed Python3 incompatibility.
Fixed tox problems. Now it runs fine.

**Comment by BenWhitehead** [comment]
Awesome! is there a new build we can point to in universe to make sure the updated code is used?

**Comment by dmitrypekar** [comment]
It is already on AWS S3 in the correct location.
We are not released yet, so I've just updated the tar-ball there.

**Comment by BenWhitehead** [comment]
Okay thanks,
I've tested this on an EA5 Pre-release build and it was able to connect through the dcos admin router.

This should be okay to merge when you're ready.

**Comment by dmitrypekar** [comment]
Please merge, if the connectivity problem is resolved. Changes are only related to that
and fixing tests and code formatting.

**Comment by dmitrypekar** [comment]
Ok. I see a cluster link in email. Will test now.

**Comment by dmitrypekar** [comment]
So I've checked connectivity and it works fine. You can merge now.

**Pull request merged**
