### PR TITLE
support for configurable kafka scheduler api url

### PR DESCRIPTION
**Pull request by ryane**

### CODE REVIEW

**Comment by elingg** [comment]
hello @dmitrypekar or @joestein could you please review and merge this PR? Thanks! Please let me know if you don't have access to this repo and I can add you. Joe should have access.

**Comment by dmitrypekar** [comment]
Hi @elingg 
Unfortunately, we have no write-access to this repo and only mesosphere team is able to merge this PR.
So either I need write-access or someone from mesosphere team should merge this.

Regarding the PR itself. It seems to be working, but I am not sure about the rationale behind those function. Do we really need those function?

**Comment by ryane** [comment]
A little context: on a non-dcos cluster, we are able to install the kafka package using dcos-cli. However, we are not able to use the dcos-kafka subcommand (as-is) because the url is hardcoded. Our service discovery makes the kafka scheduler api available at something like `https://kafka.example.com`. So it would be nice if we could configure this url so that we could use the dcos-kafka subcommand to manage brokers.

This would also be consistent with the core dcos-cli as it provides the ability to configure the mesos and marathon urls: https://github.com/mesosphere/dcos-cli#using-the-cli-without-dcos.

**Comment by elingg** [comment]
@dmitrypekar, I gave Joe access to this repo specifically. I will create a ticket to get you access as well. Meanwhile, if you approve I will merge.

**Comment by dmitrypekar** [comment]
@elingg 
Ok, now the rationale is clear. I've tried the changes. And they worked fine.
I was testing using dcos cli agains my local mesos/marathon environment (without dcos).

Please merge this PR. After merging we will need to update dcos-kafka package on AWS (referenced from universe) and maybe the universe entry itself. Should I just replace package on AWS with the new one (https://s3-us-west-2.amazonaws.com/kafka-mesos/dcos-kafka-0.1.0.tar.gz) or update it version and send PR to universe project?

**Comment by joestein** [comment]
shouldn't those packages be immutable and addition like the repository for services is too? wherever the right repo is to talk about that lets create an issue there and reference back here then close

**Comment by elingg** [comment]
Thanks @joestein and @dmitrypekar, that sounds good. When you roll out the new version in universe, you should update the packaging. We are doing our best to do incremental updates instead of overriding tarballs.

**Comment by elingg** [comment]
Also, we may want to start cutting releases for this repo as well. Eventually we'll also have automated builds for dcos-kafka along with our other service CLI's as well.

**Comment by elingg** [comment]
@dmitrypekar, you should have received an invitation for access

**Pull request merged**
